version: '3.4'

services:
  apiservice:
    image: ${DOCKER_REGISTRY-}apiservice
    container_name: apiservice 
    ports:
        - "32772:32773"

    build:
      context: .
      dockerfile: ApiService/Dockerfile
networks:  
    default:  
        external:  
            name:  jar-container-network 
