apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientservice-deployment
spec:
  selector:
    matchLabels:
      app: clientservice-pod
  template:
    metadata:
      labels:
        app: clientservice-pod
    spec:
      containers:
        - name: clientservice-container
          image: nameservice.azurecr.io/clientservice:latest
          ports:
            - containerPort: 80